# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master
- dev

pr:
  autoCancel: true
  branches:
    include:
      - master
      - dev

pool:
  vmImage: 'ubuntu-latest'

steps:
- bash: |
    export DISPLAY=:99.0
    sh -e /etc/init.d/xvfb start
    sleep 3 # give xvfb some time to start
  displayName: 'Preparing environment for JavaFX initialization possibility'
- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build --stacktrace --info'
    publishJUnitResults: true
    testResultsFiles: '**/test/index.html'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    gradleOptions: '-Xmx3072m'